image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - docker login registry.gitlab.com -u MattDierick -p $matt_token

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mattdierick/arcadia-application/App2/app2 .
    - docker push registry.gitlab.com/mattdierick/arcadia-application/App2/app2
